# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harbor < Formula
  desc ""
  homepage "https://github.com/harbor-xyz/harbor-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/harbor-xyz/harbor-cli/releases/download/v0.2.0/harbor-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "4383a3072d93189eac785b62fdbdab89abad682121f8521060cebe7d1e263fc7"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/harbor-xyz/harbor-cli/releases/download/v0.2.0/harbor-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "2b7f48cf760f3ecd69e7c172863b2e7f1b61b7169238fda517d68541d5414053"

      def install
        bin.install "harbor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harbor-xyz/harbor-cli/releases/download/v0.2.0/harbor-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "dbf9e55dc974be58523307b32df61062cbf2edc81fc77c6397b33b66cbf73e40"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/harbor-xyz/harbor-cli/releases/download/v0.2.0/harbor-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "2344012dc4bdcc6121c91a3c848abc6f38ca7f24e54407cdd8744596a3a4eb55"

      def install
        bin.install "harbor"
      end
    end
  end
end
