# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harbor < Formula
  desc ""
  homepage "https://github.com/harbor-xyz/harbor-cli"
  version "0.2.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/harbor-xyz/harbor-cli/releases/download/v0.2.10/harbor-cli_0.2.10_darwin_arm64.tar.gz"
      sha256 "b37ba9e7a34e53736f2d60b2c3024e9736aae5db3a08b57f6f86751f5495a008"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/harbor-xyz/harbor-cli/releases/download/v0.2.10/harbor-cli_0.2.10_darwin_amd64.tar.gz"
      sha256 "1c07cbb3d0efcb711d3563581b4db69b03af88099cb2a72e0662f24aa09dde89"

      def install
        bin.install "harbor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harbor-xyz/harbor-cli/releases/download/v0.2.10/harbor-cli_0.2.10_linux_arm64.tar.gz"
      sha256 "34ef29870b25a222f141297f9e4ad8fa462f62a9539c4de69d0cdea4b24c67f0"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/harbor-xyz/harbor-cli/releases/download/v0.2.10/harbor-cli_0.2.10_linux_amd64.tar.gz"
      sha256 "b1e01f8cc2feadacb1576dcfa43b99796e622c60c7a10ddfe9b31ed172cfcde6"

      def install
        bin.install "harbor"
      end
    end
  end
end
