# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monorepo < Formula
  desc ""
  homepage "https://github.com/harbor-xyz/monorepo"
  version "0.1.1"

  on_macos do
    url "https://github.com/harbor-xyz/monorepo/releases/download/v0.1.1/monorepo_0.1.1_darwin_all.tar.gz"
    sha256 "b3e7eb0e54cc7771c87ec9a9ced7027e00af470b7aff3c21df2d5dff7af8c86f"

    def install
      bin.install "monorepo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harbor-xyz/monorepo/releases/download/v0.1.1/monorepo_0.1.1_linux_arm64.tar.gz"
      sha256 "3b60ace9b36158712b43652888e47325029ba9dac7afb6bb345d5b68645e2e40"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/harbor-xyz/monorepo/releases/download/v0.1.1/monorepo_0.1.1_linux_amd64.tar.gz"
      sha256 "0411651a300bdfcb713cd5ec6dcb28030fab3fb3bf72d628143b8ccd729b27a3"

      def install
        bin.install "harbor"
      end
    end
  end
end
