# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monorepo < Formula
  desc ""
  homepage "https://github.com/harbor-xyz/harbor-cli"
  version "0.1.2"

  on_macos do
    url "https://github.com/harbor-xyz/monorepo/releases/download/v0.1.2/monorepo_0.1.2_darwin_all.tar.gz"
    sha256 "8f8dc555de465a7a2d87ad755801e296aecd80eeb2aee8ad050558e15c057dda"

    def install
      bin.install "monorepo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harbor-xyz/monorepo/releases/download/v0.1.2/monorepo_0.1.2_linux_arm64.tar.gz"
      sha256 "5048209e8383adca43d57005a9972ea0f3efa717e55cbe10924acfbd98a15d7f"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/harbor-xyz/monorepo/releases/download/v0.1.2/monorepo_0.1.2_linux_amd64.tar.gz"
      sha256 "9e16888dfd235eaf09194482fe4fff6b0fae6f7dbaad8837ac7b144b3208dec9"

      def install
        bin.install "harbor"
      end
    end
  end
end
